### PR TITLE
simple command to see the generated html from a jade template with ⌘B

### PR DESCRIPTION
**Pull request by jrus**
probably could be made more complex later, but this is a reasonable start. Might also be worth adding a "preview" command to show the rendered html instead of the html source.

### CODE REVIEW

**Comment by tj** [comment]
hmm it would fail in most cases anyway if they have vars

**Comment by jrus** [comment]
that's true. it's nice to be able to select a chunk of text and see immediately how it will render though. feel free not to pull. :-)

**Comment by ThisIsMissEm** [comment]
@visionmedia i'm going to add you as a collaborator on this repo so you can keep it up-to-date if you wish.

**Comment by tj** [comment]
sounds good, the only main thing I think it is missing is to consider the text after `-` and `=` javascript

**Pull request closed without merging**
